# Generated by Django 4.0.4 on 2022-05-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='bat_file',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
