# Generated by Django 4.0.4 on 2022-05-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_script_bat_file_alter_script_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='bat_file',
            field=models.FileField(upload_to=''),
        ),
    ]
