# Generated by Django 4.0.4 on 2022-05-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_script_bat_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scriptset',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
